### ISSUE TITLE
IDE Extension causes IDE crash - VS 2019 for Mac

### ISSUE THREAD

**Issue by aormsby** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#356]
A reliable editor crash occurs in the latest VS 2019 for Mac update that makes Gorilla unusable for me at the moment. Basically, the editor crashes when I click 'Tools' menu dropdown. Repro steps follow, log file attached.

---

1) Open VS 2019 Community for Mac
2) See project selection window pop up
       ---> At this point I can open 'Tools' menu fine
3) Open a project, wait for everything to load (happens with any project)
4) Click 'Tools' in the top menu to open the 'Tools' dropdown
5) Entire editor crashes and disappears

**MacBook Air (Mid 2013), Mojave 10.14.5
Visual Studio for Mac - Community - Versions 8.1.3 (build 19)**

---

Log File - [Ide.2019-07-01__18-02-47.log](https://github.com/UXDivers/Gorilla-Player-Support/files/3345696/Ide.2019-07-01__18-02-47.log)

---

Note: I was told on the VS developer support forum that recent API changes in VS for Mac 8.1 are breaking third party extensions. I can't say anything else on that, but maybe it helps you out.

**Comment by felipefrg** [comment]
Same problem here!!!

MacBook Pro (Mid 2012) Mojave 10.14.5
Visual Studio for Mac Community - Version 8.1.3 (build 19)

Mono Framework MDK
Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028


Xamarin.Android
Version: 9.3.0.23 (Visual Studio Community)
Commit: HEAD/d0b48056f
Android SDK: /Users/felipe/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Xamarin.iOS
Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

Xamarin Designer
Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by LeoHere** [comment]
@felipefrg @aormsby I was able to reproduce the issue. I will dig into it and let you know.

**Comment by LeoHere** [comment]
UPDATE:
@aormsby @felipefrg with VS for Mac 8.1.4 (build 5) the problem disappears. However the follow me is broken. You will need to use the "Stick to this".

I will dig into the Follow me issue and let you know.

**Comment by UnreachableCode** [comment]
I can confirm that the bug @aormsby reported is affecting me on 8.1.5. Open the tools menu and the app crashes. Using your latest download from here @LeoHere https://drive.google.com/drive/u/1/folders/1ic4f_NBuvaGfenRtg-W3MIgYKDTh8qiW

**Comment by mariuszdybala** [comment]
It doesn't work for me at all. I'm not even able to open "Tool" tab item - once I do this the IDE is crashed.
(Visual studio for Mac 8.2 build 1105)

**Comment by andreabalducci** [comment]
same here. I can run VS on Mac only unchecking the "Follow me" settings in tools menu, otherwise vs crashes when I open a solution.

Crash occurs when I try to show the current opened XAML in gorilla player.
Let me know if you need the crash logs.

=== Visual Studio Professional 2019 for Mac ===

Version 8.2.2 (build 21)
Installation UUID: adf70680-d129-410d-addc-d85c0461419c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000319

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.319 (2019-02/52203786470) (64-bit)
	Package version: 600000319

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-preview6-27804-01
	2.2.6
	2.2.0
	2.1.9
	2.1.2
SDK: /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks
SDK Versions:
	3.0.100-preview6-012264
	2.2.301
	2.2.101
	2.1.505
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Professional)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Professional)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Professional)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/andrea/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/andrea/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-30 21:29:36 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802020021
Git revision: d2ffd09000c5d24a206b715b63d409e8e965689a
Build date: 2019-08-02 00:25:49+00
Build branch: release-8.2
Xamarin extensions: 4cc9cbbe68baaeb6bc654f36e057b1bd124f3f65

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Gorilla Player 1.5.2.0

**Comment by andreabalducci** [comment]
And vs instances keep running in background at restart

<img width="446" alt="image" src="https://user-images.githubusercontent.com/212729/62615265-3e277f00-b90d-11e9-9f65-a572d83c7ee7.png">

**Comment by LeoHere** [comment]
@aormsby @andreabalducci @mariuszdybala @UnreachableCode @felipefrg 
Please install [this](https://drive.google.com/drive/folders/1KhckKlgYgZz_cSaDJRxxNPiVFWJVYf4J) version of Gorilla from the dev branch. It should fix all issues in VS for Mac. Be sure to install the VS for Mac addin during the installation.

**Comment by andreabalducci** [comment]
@LeoHere worked for me. thank you!

**Comment by eranda1985** [comment]
Yep. Works with VS Mac v8.2.2. Thank You @LeoHere !!.

**Comment by LeoHere** [comment]
Closing the issue now. Feel free to open it again if you need to.
